openapi: "3.0.0"
info:
  version: 1.0.0
  title: Web Runner Configurer
  description: A CRUD API that configurate tasks activate by web url
  contact:
    name: Eugeny Birukov
    email: ebirukov@perfectplaystudio.com
servers:
  - url: http://localhost:8080
paths:
  /configs:
    get:
      operationId: findTaskConfigs
      responses:
        '200':
          description: list of task config response
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/TaskConfig'
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/OperationError'
    post:
      description: Add a new task config to repository
      operationId: addTaskConfig
      requestBody:
        description: Task config to add to repository
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/NewConfig'
      responses:
        '200':
          description: task config response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TaskConfig'
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/OperationError'
  /configs/{id}:
    get:
      description: Return a task configuration by id
      operationId: findTaskConfigById
      parameters:
        - name: id
          in: path
          description: id of task config to fetch
          required: true
          schema:
            type: integer
            format: int64
      responses:
        '200':
          description: task config response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TaskConfig'
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/OperationError'
    post:
      description: Update a task config by id
      operationId: updateTaskConfig
      parameters:
        - name: id
          in: path
          description: id of task config to delete
          required: true
          schema:
            type: integer
            format: int64
      requestBody:
        description: Task config to update in repository
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/NewConfig'
      responses:
        '200':
          description: updated task config response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TaskConfig'
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/OperationError'
    delete:
      description: deletes a task configuration from repository by Id
      operationId: deleteTaskConfig
      parameters:
        - name: id
          in: path
          description: id of task config to delete
          required: true
          schema:
            type: integer
            format: int64
      responses:
        '204':
          description: task config deleted
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/OperationError'
components:
  schemas:
    TaskConfig:
      allOf:
        - $ref: '#/components/schemas/NewConfig'
        - type: object
          required:
            - id
          properties:
            id:
              type: integer
              format: int64

    NewConfig:
      type: object
      required:
        - path
        - taskdefinition
        - container
        - script
      properties:
        path:
          type: string
          description: url path name that route to execution script result
        taskDefinition:
          type: string
          description: definition name of container task
          x-oapi-codegen-extra-tags:
            gorm: column:taskDefinition
        container:
          type: string
          description: container name of ecs task
        category:
          type: string
        script:
          type: string
          description: executed script path
        cluster:
          type: string
        desc:
          type: string

    OperationError:
      type: object
      required:
        - code
        - message
      properties:
        code:
          type: integer
          format: int32
        message:
          type: string
