// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/deepmap/oapi-codegen version v1.8.2 DO NOT EDIT.
package api

// NewConfig defines model for NewConfig.
type NewConfig struct {
	Category   *string `json:"category,omitempty"`
	Cluster    *string `json:"cluster,omitempty"`
	Container  string  `json:"container"`
	Desc       *string `json:"desc,omitempty"`
	ScriptPath string  `json:"scriptPath"`
	TaskDef    string  `json:"taskDef"`
	UrlPath    string  `json:"urlPath"`
}

// OperationError defines model for OperationError.
type OperationError struct {
	Code    int32  `json:"code"`
	Message string `json:"message"`
}

// TaskConfig defines model for TaskConfig.
type TaskConfig struct {
	// Embedded struct due to allOf(#/components/schemas/NewConfig)
	NewConfig `yaml:",inline"`
	// Embedded fields due to inline allOf schema
	Id int64 `json:"id"`
}

// FindTaskConfigsParams defines parameters for FindTaskConfigs.
type FindTaskConfigsParams struct {
	// url path to filter by
	UrlPath *[]string `json:"urlPath,omitempty"`

	// maximum number of results to return
	Limit *int32 `json:"limit,omitempty"`
}

// AddTaskConfigJSONBody defines parameters for AddTaskConfig.
type AddTaskConfigJSONBody NewConfig

// AddTaskConfigJSONRequestBody defines body for AddTaskConfig for application/json ContentType.
type AddTaskConfigJSONRequestBody AddTaskConfigJSONBody
