// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/deepmap/oapi-codegen version v1.8.2 DO NOT EDIT.
package api

import (
	"bytes"
	"compress/gzip"
	"encoding/base64"
	"fmt"
	"net/http"
	"net/url"
	"path"
	"strings"

	"github.com/deepmap/oapi-codegen/pkg/runtime"
	"github.com/getkin/kin-openapi/openapi3"
	"github.com/labstack/echo/v4"
)

// ServerInterface represents all server handlers.
type ServerInterface interface {

	// (GET /configs)
	FindTaskConfigs(ctx echo.Context, params FindTaskConfigsParams) error

	// (POST /configs)
	AddTaskConfig(ctx echo.Context) error

	// (DELETE /configs/{id})
	DeleteTaskConfig(ctx echo.Context, id int64) error

	// (GET /configs/{id})
	FindTaskConfigById(ctx echo.Context, id int64) error
}

// ServerInterfaceWrapper converts echo contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler ServerInterface
}

// FindTaskConfigs converts echo context to params.
func (w *ServerInterfaceWrapper) FindTaskConfigs(ctx echo.Context) error {
	var err error

	// Parameter object where we will unmarshal all parameters from the context
	var params FindTaskConfigsParams
	// ------------- Optional query parameter "urlPath" -------------

	err = runtime.BindQueryParameter("form", true, false, "urlPath", ctx.QueryParams(), &params.UrlPath)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter urlPath: %s", err))
	}

	// ------------- Optional query parameter "limit" -------------

	err = runtime.BindQueryParameter("form", true, false, "limit", ctx.QueryParams(), &params.Limit)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter limit: %s", err))
	}

	// Invoke the callback with all the unmarshalled arguments
	err = w.Handler.FindTaskConfigs(ctx, params)
	return err
}

// AddTaskConfig converts echo context to params.
func (w *ServerInterfaceWrapper) AddTaskConfig(ctx echo.Context) error {
	var err error

	// Invoke the callback with all the unmarshalled arguments
	err = w.Handler.AddTaskConfig(ctx)
	return err
}

// DeleteTaskConfig converts echo context to params.
func (w *ServerInterfaceWrapper) DeleteTaskConfig(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "id" -------------
	var id int64

	err = runtime.BindStyledParameterWithLocation("simple", false, "id", runtime.ParamLocationPath, ctx.Param("id"), &id)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter id: %s", err))
	}

	// Invoke the callback with all the unmarshalled arguments
	err = w.Handler.DeleteTaskConfig(ctx, id)
	return err
}

// FindTaskConfigById converts echo context to params.
func (w *ServerInterfaceWrapper) FindTaskConfigById(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "id" -------------
	var id int64

	err = runtime.BindStyledParameterWithLocation("simple", false, "id", runtime.ParamLocationPath, ctx.Param("id"), &id)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter id: %s", err))
	}

	// Invoke the callback with all the unmarshalled arguments
	err = w.Handler.FindTaskConfigById(ctx, id)
	return err
}

// This is a simple interface which specifies echo.Route addition functions which
// are present on both echo.Echo and echo.Group, since we want to allow using
// either of them for path registration
type EchoRouter interface {
	CONNECT(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	DELETE(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	GET(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	HEAD(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	OPTIONS(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	PATCH(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	POST(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	PUT(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	TRACE(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
}

// RegisterHandlers adds each server route to the EchoRouter.
func RegisterHandlers(router EchoRouter, si ServerInterface) {
	RegisterHandlersWithBaseURL(router, si, "")
}

// Registers handlers, and prepends BaseURL to the paths, so that the paths
// can be served under a prefix.
func RegisterHandlersWithBaseURL(router EchoRouter, si ServerInterface, baseURL string) {

	wrapper := ServerInterfaceWrapper{
		Handler: si,
	}

	router.GET(baseURL+"/configs", wrapper.FindTaskConfigs)
	router.POST(baseURL+"/configs", wrapper.AddTaskConfig)
	router.DELETE(baseURL+"/configs/:id", wrapper.DeleteTaskConfig)
	router.GET(baseURL+"/configs/:id", wrapper.FindTaskConfigById)

}

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/+xWTY/bNhD9KwTbo7F2k6AIdOp+pMBemmCRoodgDyNxZDNLkcxw6I1g6L8XpOyVZcmb",
	"Bi2KPeRkmh/DN/PePGonK9d4Z9FykMVOhmqDDeThH/h47Wyt1+mPJ+eRWGNeqoBx7ahNY249ykIGJm3X",
	"slvIysTASPNrzjJoe2ZVYahmF0JF2vMH4M3sMkN4uMF6di2SOXOuW0jCL1ETKll8eto4hDuGO8JwvzjE",
	"cuVnrDjd894jAWtn3xE5mimZU5h+a0cNsCyktvz6lXyKpC3jGimFajAEWOO3IeeYw/45WB8hPAwsgjHv",
	"a1l82smfKdVL/rQc6F/uuV8OxHeL0zS0Ok3i1zczSZwA1WoG3H2Xtmlbu74+lqHiNMQGtJGFxFJTfHDb",
	"3zxSjRV7A23gqLS7qFwjF9JCkwK+i2u0rbjqdx+ElNjSzspCXorruz9vxOWHW8EbYFHl5CIBo0hcBwEV",
	"6236W7biEUsRyaSkNJsU/y8sxV20Fklc749mRWyRQn/DLxeri1W62Hm04LUs5Os8tZAeeJMrt+yvzeM1",
	"5kTdQTO3Shbyd23VQFfIZwkaZKSQORtnFcmIFFywE7U2jCTKVqaCykJ+iUjtUKFB2z3HmUnGJsy3Uz8B",
	"RNDm7uM21yGxniUxBtLAV93ERtjYlEjC1YIwRMMhISPkSPYMLKMbzSNQ3+yO7j4pK3hnQy/IV6vVQT5o",
	"c1XBe6OrXNfl55Ag7ubSfq4DjrpmUo9uoi+jA6e0k5b24hIHjL0aa4iGvwvmc+hOrGYGUbT41WPFqAQO",
	"e7wL+eaT7lBKgLD4OMLPTihgKCEkhxkL9VId6VT2nY6Br5xq/7Mcjzxomt7HMVBQ6gTv4D1MEbt/KZl/",
	"qpQp0JetiG7xZErLnVZdrw2DjFOV9PNBwLFKYn9pcs1bNZHJTT4yUsqzhqbVaRMlUns8e//wvYnt7UOr",
	"CdXnvGT+kZp6yZtp5seAejTqJTX1/ikZb73LrnuWLD0la/z4XLWZz++nq0auNv8bWz/aOLdxeqKRtgea",
	"0sdLITfMvlgujavAbFzg4u3q7Sp9dP0dAAD//5HW9FryCwAA",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %s", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %s", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %s", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	var res = make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	var resolvePath = PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		var pathToFile = url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
